/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sales.view;

import java.util.List;
import javax.swing.JOptionPane;
import org.sales.controller.ProductDAO;
import org.sales.model.Product;
//import java.sales.model.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIT
 */
public class ViewProduct extends javax.swing.JInternalFrame {

   DefaultTableModel model;
    public ViewProduct() {
        initComponents();
        model=new DefaultTableModel(null,new String[]{"ID","NAME","PRICE","QTY","REMARKS"});
        jTable_Product.setModel(model);
    }
    public void loadData()
    {
        ProductDAO pDAO=new ProductDAO();
            List<Product>productList=pDAO.fetchData();
            clearTable();
            for(Product p:productList)
            {
                
                model.addRow(new Object[]{
                    p.getId(),p.getName(),p.getPrice(),p.getQty(),p.getRemarks()});
            }
    }
    public void clearFields()
    {
        //jTextField_EID.setText("");
        jTextField_EName.setText("");
        jTextField_EPrice.setText("");
        jTextField_EQty.setText("");
        jTextArea_ERemarks.setText("");
    }
    public void clearTable()
    {
        int count=jTable_Product.getRowCount();
        for(int i=0;i<count;i++)
        {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jButton_LoadData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_EName = new javax.swing.JTextField();
        jTextField_EPrice = new javax.swing.JTextField();
        jTextField_EQty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ERemarks = new javax.swing.JTextArea();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_EId = new javax.swing.JTextField();

        setClosable(true);

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Product);

        jButton_LoadData.setText("Load Data");
        jButton_LoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadDataActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Price");

        jLabel3.setText("Qty");

        jLabel4.setText("Remarks");

        jTextArea_ERemarks.setColumns(20);
        jTextArea_ERemarks.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ERemarks);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("Id");

        jTextField_EId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LoadData))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_EName)
                            .addComponent(jTextField_EId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Update)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Delete))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jTextField_EQty)
                            .addComponent(jTextField_EPrice))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_EId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_EName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_EPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_EQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton_LoadData)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Update)
                            .addComponent(jButton_Delete))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadDataActionPerformed
            //call fetchData() method of controller class
            loadData();
    }//GEN-LAST:event_jButton_LoadDataActionPerformed

    private void jTable_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProductMouseClicked
       
        int row=jTable_Product.getSelectedRow();
        jTextField_EId.setText(jTable_Product.getValueAt(row,0).toString());
        jTextField_EName.setText(jTable_Product.getValueAt(row,1).toString());
        jTextField_EPrice.setText(jTable_Product.getValueAt(row,2).toString());
        jTextField_EQty.setText(jTable_Product.getValueAt(row,3).toString());
        jTextArea_ERemarks.setText(jTable_Product.getValueAt(row,4).toString());
    }//GEN-LAST:event_jTable_ProductMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
       int id=Integer.parseInt(jTextField_EId.getText());
       String name=jTextField_EName.getText();
        double price =Double.parseDouble(jTextField_EPrice.getText());
        int qty =Integer.parseInt(jTextField_EQty.getText());
        String remarks=jTextArea_ERemarks.getText();
        //Set These Values In the "Model Class- product " Object
        Product ob=new Product();
        ob.setId(id);
        ob.setName(name);
        ob.setPrice(price);
        ob.setQty(qty);
        ob.setRemarks(remarks);
        
        //Now handover This Object To the "Contoller Class  ProductDAO"
        ProductDAO pDAO=new ProductDAO();
       int count = pDAO.updateData(ob);
        if(count>0)
        {
            JOptionPane.showMessageDialog(null,"Record Updated");
            loadData();
        }
        clearFields();
    
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        int id=Integer.parseInt(jTextField_EId.getText());
       String name=jTextField_EName.getText();
        double price =Double.parseDouble(jTextField_EPrice.getText());
        int qty =Integer.parseInt(jTextField_EQty.getText());
        String remarks=jTextArea_ERemarks.getText();
        //Set These Values In the "Model Class- product " Object
        Product ob=new Product();
        ob.setId(id);
        ob.setName(name);
        ob.setPrice(price);
        ob.setQty(qty);
        ob.setRemarks(remarks);
        
        //Now handover This Object To the "Contoller Class  ProductDAO"
        ProductDAO pDAO=new ProductDAO();
       int count = pDAO.deleteData(ob);
        if(count>0)
        {
            JOptionPane.showMessageDialog(null,"Record deleted");
            loadData();
        }
        clearFields();
    }//GEN-LAST:event_jButton_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_LoadData;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Product;
    private javax.swing.JTextArea jTextArea_ERemarks;
    private javax.swing.JTextField jTextField_EId;
    private javax.swing.JTextField jTextField_EName;
    private javax.swing.JTextField jTextField_EPrice;
    private javax.swing.JTextField jTextField_EQty;
    // End of variables declaration//GEN-END:variables
}
